import { IMG_BASE } from "@/data/landingShowcase";

// Responsive srcset builders. Variants are pre-generated by
// scripts/responsive-images.mjs; the untouched master (~1000px) is the largest
// candidate so big slots get full resolution while small tiles pull a fraction
// of the bytes. Lossless in practice — the browser just picks the right size.

/** Square /landing/* showcase tiles. */
export const landingSrcSet = (png: number) =>
  `${IMG_BASE}${png}-256.webp 256w, ${IMG_BASE}${png}-512.webp 512w, ${IMG_BASE}${png}.webp 1000w`;

/** /images/* photos that have -360 / -600 variants. */
export const photoSrcSet = (name: string) =>
  `/images/${name}-360.webp 360w, /images/${name}-600.webp 600w, /images/${name}.webp 1000w`;
