// Optimize landing-showcase images into public/landing and emit a typed data module.
// node scripts/landing-build.mjs
import sharp from "sharp";
import fs from "node:fs";
import path from "node:path";

const SRC = "C:/Users/direc/Dropbox/Ambiente Home LLC/Website/rebrand1/Landing Images";
const OUTDIR = "public/landing";
const MAP = JSON.parse(fs.readFileSync("scripts/landing-image-map.json", "utf8"));

// prefer LIFESTYLE variant when a png has both
const byPng = new Map();
for (const r of MAP) {
  const cur = byPng.get(r.png);
  if (!cur || (r.variant === "LIFESTYLE" && cur.variant !== "LIFESTYLE")) byPng.set(r.png, r);
}

const norm = (t) => {
  const s = (t || "").toLowerCase();
  for (const k of ["necklace", "pendant", "earring", "bracelet", "charm", "watch", "ring", "sunglass", "hair"])
    if (s.includes(k)) return k === "pendant" ? "necklace" : k;
  return "?";
};
const ROUTE = { bracelet: "/bracelets", necklace: "/necklaces", charm: "/charms", ring: "/rings", earring: "/earrings", watch: "/watches", hair: "/hair", sunglass: "/sunglasses" };
const LABEL = { bracelet: "Bracelets", necklace: "Necklaces", charm: "Charms", ring: "Rings", earring: "Earrings", watch: "Watches", hair: "Hair", sunglass: "Sunglasses" };

fs.mkdirSync(OUTDIR, { recursive: true });
const sized = new Set();
async function opt(png, size) {
  const r = byPng.get(png);
  if (!r) { console.log("MISSING", png); return false; }
  if (!sized.has(png)) {
    await sharp(path.join(SRC, r.file)).resize(size, size, { fit: "cover" }).webp({ quality: 74 }).toFile(path.join(OUTDIR, `${png}.webp`));
    sized.add(png);
  }
  return true;
}
const cat = (p) => norm(byPng.get(p)?.type);
const handle = (p) => byPng.get(p)?.handle;

const carouselPlan = [201, 173, 232, 67, 292, 1039, 804, 732];
const bannerPlan = [423, 160, 75, 493, 38, 263, 174, 585, 507];
const howtoPlan = [
  { png: 1001, step: "01 · the ear", h: "Let gravity stylize.", p: "Heaviest piece low, a dainty stud mid, a thin huggie up high — three pieces descending in weight." },
  { png: 447, step: "02 · the neckline", h: "Three lengths, layered.", p: "A snug chain, a beaded strand, a pendant below — about two inches apart so every layer is seen." },
  { png: 909, step: "03 · the wrist", h: "Plant a wrist garden.", p: "A slim chain, a colourful bead strand, a structured cuff. Texture is the trick, not quantity." },
  { png: 870, step: "04 · the hand", h: "Odd numbers, never symmetry.", p: "Three rings or five across both hands — never even, never mirrored. Leave one finger bare on purpose." },
];
const gridRows = [
  [165, 254, 475, 494, 831, 939],
  [382, 973, 972, 33, 320, 301],
  [645, 192, 551, 545, 607, 853],
  [221, 229, 232, 263, 335, 339],
];

const carousel = [];
for (const png of carouselPlan) { await opt(png, 1000); const c = cat(png); carousel.push({ png, label: LABEL[c], route: ROUTE[c] }); }
const banner = [];
for (const png of bannerPlan) { await opt(png, 680); banner.push({ png, href: "/product/" + handle(png) }); }
const howto = [];
for (const t of howtoPlan) { await opt(t.png, 760); const c = cat(t.png); howto.push({ png: t.png, step: t.step, h: t.h, p: t.p, label: LABEL[c], route: ROUTE[c] }); }
const grid = [];
for (const row of gridRows) {
  const r = [];
  for (const png of row) { await opt(png, 540); r.push({ png, href: "/product/" + handle(png) }); }
  grid.push(r);
}

const ts = `// AUTO-GENERATED by scripts/landing-build.mjs — do not edit by hand.
export const IMG_BASE = "/landing/";
export interface ShowcaseSlide { png: number; label: string; route: string }
export interface ShowcaseImg { png: number; href: string }
export interface HowToCard { png: number; step: string; h: string; p: string; label: string; route: string }
export const carousel: ShowcaseSlide[] = ${JSON.stringify(carousel, null, 2)};
export const banner: ShowcaseImg[] = ${JSON.stringify(banner, null, 2)};
export const howto: HowToCard[] = ${JSON.stringify(howto, null, 2)};
export const grid: ShowcaseImg[][] = ${JSON.stringify(grid, null, 2)};
`;
fs.writeFileSync("src/data/landingShowcase.ts", ts);
console.log("images:", sized.size, "-> public/landing");
console.log("wrote src/data/landingShowcase.ts");
