// AUTO-GENERATED by scripts/landing-build.mjs — do not edit by hand.
export const IMG_BASE = "/landing/";
export interface ShowcaseSlide { png: number; label: string; route: string }
export interface ShowcaseImg { png: number; href: string }
export interface HowToCard { png: number; step: string; h: string; p: string; label: string; route: string }
export const carousel: ShowcaseSlide[] = [
  {
    "png": 201,
    "label": "Bracelets",
    "route": "/bracelets"
  },
  {
    "png": 173,
    "label": "Necklaces",
    "route": "/necklaces"
  },
  {
    "png": 232,
    "label": "Charms",
    "route": "/charms"
  },
  {
    "png": 67,
    "label": "Rings",
    "route": "/rings"
  },
  {
    "png": 292,
    "label": "Earrings",
    "route": "/earrings"
  },
  {
    "png": 1039,
    "label": "Watches",
    "route": "/watches"
  },
  {
    "png": 804,
    "label": "Hair",
    "route": "/hair"
  },
  {
    "png": 732,
    "label": "Sunglasses",
    "route": "/sunglasses"
  }
];
export const banner: ShowcaseImg[] = [
  {
    "png": 423,
    "href": "/product/zealia-earrings423"
  },
  {
    "png": 160,
    "href": "/product/geolia-necklace160"
  },
  {
    "png": 75,
    "href": "/product/raevia-ring75"
  },
  {
    "png": 493,
    "href": "/product/maelvia-necklace493"
  },
  {
    "png": 38,
    "href": "/product/maelina-earrings38"
  },
  {
    "png": 263,
    "href": "/product/liomia-charm263"
  },
  {
    "png": 174,
    "href": "/product/gaevia-necklace174"
  },
  {
    "png": 585,
    "href": "/product/ziomia-bracelet585"
  },
  {
    "png": 507,
    "href": "/product/raennia-necklace507"
  }
];
export const howto: HowToCard[] = [
  {
    "png": 1001,
    "step": "01 · the ear",
    "h": "Let gravity stylize.",
    "p": "Heaviest piece low, a dainty stud mid, a thin huggie up high — three pieces descending in weight.",
    "label": "Earrings",
    "route": "/earrings"
  },
  {
    "png": 447,
    "step": "02 · the neckline",
    "h": "Three lengths, layered.",
    "p": "A snug chain, a beaded strand, a pendant below — about two inches apart so every layer is seen.",
    "label": "Necklaces",
    "route": "/necklaces"
  },
  {
    "png": 909,
    "step": "03 · the wrist",
    "h": "Plant a wrist garden.",
    "p": "A slim chain, a colourful bead strand, a structured cuff. Texture is the trick, not quantity.",
    "label": "Bracelets",
    "route": "/bracelets"
  },
  {
    "png": 870,
    "step": "04 · the hand",
    "h": "Odd numbers, never symmetry.",
    "p": "Three rings or five across both hands — never even, never mirrored. Leave one finger bare on purpose.",
    "label": "Rings",
    "route": "/rings"
  }
];
export const grid: ShowcaseImg[][] = [
  [
    {
      "png": 165,
      "href": "/product/raevia-necklace165"
    },
    {
      "png": 254,
      "href": "/product/raevia-necklace254"
    },
    {
      "png": 475,
      "href": "/product/leonia-necklace475"
    },
    {
      "png": 494,
      "href": "/product/zionia-necklace494"
    },
    {
      "png": 831,
      "href": "/product/raellia-necklace831"
    },
    {
      "png": 939,
      "href": "/product/ziolia-necklace939"
    }
  ],
  [
    {
      "png": 382,
      "href": "/product/zaelia-earrings382"
    },
    {
      "png": 973,
      "href": "/product/rionia-earrings973"
    },
    {
      "png": 972,
      "href": "/product/riolia-earrings972"
    },
    {
      "png": 33,
      "href": "/product/raelia-earrings33"
    },
    {
      "png": 320,
      "href": "/product/maevia-earrings320"
    },
    {
      "png": 301,
      "href": "/product/riovia-earrings301"
    }
  ],
  [
    {
      "png": 645,
      "href": "/product/zaevia-bracelet645"
    },
    {
      "png": 192,
      "href": "/product/maevia-bracelet192"
    },
    {
      "png": 551,
      "href": "/product/vaelia-bracelet551"
    },
    {
      "png": 545,
      "href": "/product/reolia-bracelet545"
    },
    {
      "png": 607,
      "href": "/product/zaelia-bracelet607"
    },
    {
      "png": 853,
      "href": "/product/maelia-bracelet853"
    }
  ],
  [
    {
      "png": 221,
      "href": "/product/maelina-charm221"
    },
    {
      "png": 229,
      "href": "/product/zaelina-charm229"
    },
    {
      "png": 232,
      "href": "/product/vaenia-charm232"
    },
    {
      "png": 263,
      "href": "/product/liomia-charm263"
    },
    {
      "png": 335,
      "href": "/product/thaelia-charm335"
    },
    {
      "png": 339,
      "href": "/product/maelira-charm339"
    }
  ]
];
